on:
  push:
    branches:
    - release/*
    - develop
    - feature/*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - release/*
    - develop
    - feature/*
  merge_group:
  workflow_dispatch:
name: Build and Test Development Code
jobs:
  build-artifacts:
    name: Build Java Artifacts
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write
    env:
      BUILD_SNAPSHOT: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&
                          (github.ref_name == 'develop' || startsWith(github.ref_name, 'release/')) }}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        submodules: recursive
        filter: tree:0
    # -------------------------
    # Java Environment Setup
    # -------------------------
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f
      with:
        maven-version: 3.9.3
    - id: setup-java-deploy
      name: Set up JDK 11 (deploy)
      if: ${{ env.BUILD_SNAPSHOT == 'true' }}
      uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up JDK 11 (build only)
      if:  ${{ steps.setup-java-deploy.outcome == 'skipped' }}
      uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'
    - name: Initialize CodeQL
      if: github.event_name == 'push'
      uses: github/codeql-action/init@3ab4101902695724f9365a384f86c1074d94e18c
      with:
        languages: java
    # -------------------------
    # Maven Build
    # -------------------------
    - id: build-test-deploy
      name: Build, Test and DEPLOY SNAPSHOT Code
      if: ${{ env.BUILD_SNAPSHOT == 'true' }}
      run: |
        mvn -B -e --batch-mode -Prelease -Preporting deploy -Dmaven.deploy.skip=releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Test Code
      if: ${{ steps.build-test-deploy.outcome == 'skipped' }}
      run: |
        mvn -B -e -Prelease -Preporting install
    - name: Perform CodeQL Analysis
      if: github.event_name == 'push'
      uses: github/codeql-action/analyze@3ab4101902695724f9365a384f86c1074d94e18c
      with:
        upload: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'develop' && 'always' || 'never' }}
    - name: Test Website
      run: |
        # this needs to be run as a second build to ensure source is fully generated by the previous step
        mvn -B -e -Prelease -Preporting install site site:stage
